site_name: Quantum Mechanics
site_url: https://qm.utasphys.cloud.edu.au/
repo_url: https://github.com/Andy-UTAS/qm
repo_name:  Quantum mechanics
edit_uri: ""

nav:
    - Home: index.md
    - Course particulars: particulars.md
    - '0: Introduction':
      - '0.1 - Quantum mechanics 101': 00-introduction/0-1-intro.md
    - '1: Stern-Gerlach Experiments':
      - '1.1 - The experiment': 01-stern-gerlach/1-1-exp.md
      - '1.2 - State vectors': 01-stern-gerlach/1-2-statevectors.md
    - Additional resources: additional.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: orange
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: orange
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: logo.png
  favicon: logo.png
  features:
  #  - navigation.expand
    - navigation.top # Include a "back to top" button
  # Removed for teaching  - navigation.tabs # Use tabs rather than sections
    - navigation.sections # Render sections as groups
  # Removed for teaching  - navigation.indexes # Include section index pages
    # Removed for teaching  - toc.integrate # Integrate the table of contents into the left index
    - search.highlight
    - content.code.annotate
    - content.action.view # View source code
    - announce.dismiss
  highlightjs: True
  icon:
    repo: fontawesome/brands/git-alt
#  custom_dir: overrides # Initially here for banner usage, but this was not very good

plugins:
  - mkdocs-video # allows for video
  - search # enables search
  # - encryptcontent:
      # global_password: 'thisisapassword'
  - git-revision-date-localized:
      type: date
  # - page-to-pdf

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
  - toc:
      permalink: True
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list # For definition lists
  - pymdownx.tasklist: # For lists with checkboxes
      custom_checkbox: true
  - pymdownx.highlight:
      # linenums: true # Enabeles line numbers in code
      linenums_style: pymdownx-inline # Makes the line numbers in code not shit (renders properly and copies well)
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets: # Allows for a global list of acronyms
      auto_append:
        - includes/abbreviations.md
  - pymdownx.arithmatex: # Enable MathJax
      generic: true
  - pymdownx.superfences # Enables nesting of code and content in tabs
  - pymdownx.tabbed: # Enabeles content tabs
      alternate_style: true
  - pymdownx.caret
  - pymdownx.keys # Rendering of keyboard keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - abbr
  - attr_list
  - footnotes
  - meta

extra_javascript:
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?version=4.8.0&features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Content prepared and curated by <a href="mailto:andrew.mcculloch@utas.edu.au">A J McCulloch</a>
